Repository srm-kzilla/srmkzilla-net, pull requests merged in 2023-08, with the labels that each got.

#81 Add registration success redirect
  pages/register/index.tsx
  pages/register/success.tsx
Labels: enhancement, changes-requested

#87 fix: reroute 'Know more' to events
  shared/components/home/card.tsx
Labels: review-requested

#93 fix: 404 background fix
  pages/404.tsx
Labels: bug, review-requested

#92 fix: add padding
  pages/register/index.tsx
Labels: review-requested

#95 fix: Fixed stars background
  pages/404.tsx
  pages/register/success.tsx
Labels: bug

#96 fix: socials in speaker card
  pages/events/[slug].tsx
  shared/components/events/speaker-card.tsx
Labels: bug, review-requested

#102 change tagline
  pages/events/index.tsx
Labels: good first issue, chore

#101 update testimonials
  public/images/testimonals_person1.jpg
  shared/components/services/testimonals.tsx
Labels: review-requested, chore

#103 migration to next 13
  next-env.d.ts
  package.json
  pages/_app.tsx
  shared/components/team/carousel.tsx
  tsconfig.json
  yarn.lock
Labels: chore

#110 Removes Errors
  pages/404.tsx
  pages/_app.tsx
  pages/events/index.tsx
  pages/index.tsx
  pages/projects.tsx
  pages/register/index.tsx
  pages/register/success.tsx
  pages/services.tsx
  pages/team/index.tsx
  shared/components/home/card.tsx
  shared/components/home/process.tsx
  shared/components/loader.tsx
Labels: review-requested

#109 update reviews from alumni
  lib/data/reviews.ts
  public/images/ayushashatkar.jpg
  public/images/meenakshi.jpg
  public/images/parv.jpg
Labels: review-requested
